version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-pap
    ports:
      - "18123:8123"   # HTTP interface
      - "19000:9000"   # Native TCP interface
    environment:
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ../pap-volumes/data:/var/lib/clickhouse
      - ../pap-volumes/logs:/var/log/clickhouse-server
